version: '3'

volumes:
  gunicorn_sock_vol: {}

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=twist_db
      - POSTGRES_USER=twistdbadmin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  twist:
    build:
      context: ./backend
    command: /twist/backend/startup.sh
    depends_on:
      - db
    working_dir: /twist/backend
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - gunicorn_sock_vol:/tmp

  nginx:
    build:
        context: .
        dockerfile: nginx/Dockerfile
    volumes:
      - gunicorn_sock_vol:/tmp
    ports:
      - "80:80"
    depends_on:
      - twist
